### ISSUE TITLE
shell script for running the services

### ISSUE THREAD

**Issue by travula** [vlead/ovpl#48]
Write a script which starts ADS services.

**Comment by travula** [comment]
Currently, makefile is used to start all the services related to ADS.  The idea of make is to build the executables/. We need to come with an alternative where 
a) a shell script is created. 
b) The functionality of this scripts is :
  - start all the services
  - stop all the services
  - start an individual service
 - stop an individual service.

**Comment by ambikakaul** [comment]
A simple shell script that starts and stops all the services has been implemented. Need to figure out how to start and stop an individual service.

**Comment by ambikakaul** [comment]
As per the discussion of today, following changes were made in the bash script :
1) Individual process ids are stored so that while stopping the services, a cleaner and precise code can be written and only specific processes are terminated.
2) Each service is represented as a variable,  so that it becomes easy for us to change its path or  start and stop an individual service from command prompt.

I am expecting this issue to be resolved by  tomorrow end of the day.

**Comment by ecthiender** [comment]
@ambikakaul keep updating the status of your task here.

**Comment by ambikakaul** [comment]
status() function to get status of various services has been written. Working on removing PIDs of dead processes for same service.

**Comment by ambikakaul** [comment]
Completed. Review pending.
