### ISSUE TITLE
Unable to deploy a lab on cluster automation machine using ADS

### ISSUE THREAD

**Issue by kraghupathi** [vlead/ovpl#85]
Please fix this [issue](https://gitlab.com/vlead-systems/cluster-automation/issues/20) in ADS on cluster automation machine as soon as possible.

ADS URL : http://ads.ovpl.virtual-labs.ac.in:8080/

**Comment by ksripathi** [comment]
@kraghupathi 

I will  look into it this afternoon

**Comment by kraghupathi** [comment]
Reminder

**Comment by ksripathi** [comment]
This issue is fixed by exporting proxy for `http` and `https` and by unset proxy to `localhost`
this is documented at step(13) at [link](https://github.com/vlead/setup-ovpl-centos/blob/develop/user-docs/run-ads-using-vagrant-box.org#steps-to-run-ads-service)

hence i am closing this issue 
reopen it if you face same issue
